sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t Nilutpal-2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Nilutpal-2020/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"